/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBasicPlugin, IBasicPluginInterface } from "../IBasicPlugin";

const _abi = [
  {
    inputs: [],
    name: "upgrade",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBasicPlugin__factory {
  static readonly abi = _abi;
  static createInterface(): IBasicPluginInterface {
    return new utils.Interface(_abi) as IBasicPluginInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBasicPlugin {
    return new Contract(address, _abi, signerOrProvider) as IBasicPlugin;
  }
}
