export interface Version {
  CJPY: string;
  ChainLinkMock: string;
  Currency: string;
  CurrencyOS: string;
  Dependencies: string;
  FeePool: string;
  Import: string;
  Interfaces: string;
  Minter: string;
  OracleMockBase: string;
  Pool: string;
  PriceFeed: string;
  PriorityRegistry: string;
  ScoreRegistry: string;
  TellorCallerMock: string;
  Vester: string;
  VesterFactory: string;
  YMT: string;
  Yamato: string;
  YamatoBorrower: string;
  YamatoDepositor: string;
  YamatoRedeemer: string;
  YamatoRepayer: string;
  YamatoSweeper: string;
  YamatoWithdrawer: string;
  YmtOS: string;
  curveFork: string;
  veYMT: string;
}

export const contractVersion: Version = {
  CJPY: "CJPY",
  ChainLinkMock: "ChainLinkMock",
  Currency: "Currency",
  CurrencyOS: "CurrencyOSV2",
  Dependencies: "Dependencies",
  FeePool: "FeePool",
  Import: "Import",
  Interfaces: "Interfaces",
  Minter: "Minter",
  OracleMockBase: "OracleMockBase",
  Pool: "PoolV2",
  PriceFeed: "PriceFeedV3",
  PriorityRegistry: "PriorityRegistryV6",
  ScoreRegistry: "ScoreRegistry",
  TellorCallerMock: "TellorCallerMock",
  Vester: "Vester",
  VesterFactory: "VesterFactory",
  YMT: "YMT",
  Yamato: "YamatoV3",
  YamatoBorrower: "YamatoBorrower",
  YamatoDepositor: "YamatoDepositorV2",
  YamatoRedeemer: "YamatoRedeemerV4",
  YamatoRepayer: "YamatoRepayerV2",
  YamatoSweeper: "YamatoSweeperV2",
  YamatoWithdrawer: "YamatoWithdrawerV2",
  YmtOS: "YmtOS",
  curveFork: "curveFork",
  veYMT: "veYMT",
};
