/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IPriceFeedInterface extends ethers.utils.Interface {
  functions: {
    "fetchPrice()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "fetchPrice",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "fetchPrice", data: BytesLike): Result;

  events: {};
}

export class IPriceFeed extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPriceFeedInterface;

  functions: {
    fetchPrice(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { jpyPerUSD: BigNumber; ethPerUSD: BigNumber }
    >;
  };

  fetchPrice(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { jpyPerUSD: BigNumber; ethPerUSD: BigNumber }
  >;

  callStatic: {
    fetchPrice(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { jpyPerUSD: BigNumber; ethPerUSD: BigNumber }
    >;
  };

  filters: {};

  estimateGas: {
    fetchPrice(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    fetchPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
